"use client";

import * as React from "react";
import { useActionState } from "react";
import Link from "next/link";
import { Check, Dna, Plus, Repeat, Trash2, XCircle } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { formatDate, formatDateTime, formatQty } from "@/lib/utils";
import { updateVisitStatus, deleteVisit, type ActionResult } from "@/lib/actions/visits";
import { cancelSyncApplication } from "@/lib/actions/sync-protocols";
import { NewTreatmentDialog, animalLabel, type Product } from "@/components/gyvunai/new-treatment-dialog";
import { NewVaccinationDialog } from "@/components/vakcinacijos/new-vaccination-dialog";
import { NewInseminationDialog, type SemenProduct } from "@/components/seklinimas/new-insemination-dialog";
import { OPEN_VISIT_STATUSES, VISIT_PROCEDURE_LABELS, VISIT_STATUS_LABELS, VISIT_STATUS_TONE, vilniusDay } from "@/lib/visits";
import type { ProcedureType, SyncStepMedication, VisitProcedure, VisitStatus } from "@/lib/supabase/types";

export type VisitRecord = {
  kind: "treatment" | "vaccination" | "insemination";
  id: string;
  label: string;
  /** Diagnosis / disease (treatments), bull + pažymėjimo Nr. (insemination). */
  detail: string | null;
  /** One line per medicine given: "Penicilinas — 10 ml (i.m.)". */
  lines: string[];
  outcome: string | null;
  karencijaMilk: string | null;
  karencijaMeat: string | null;
};

export type VisitCardData = {
  id: string;
  animal_id: string;
  animal_no: string | null;
  tag_no: string;
  group_name: string | null;
  visit_datetime: string;
  procedures: VisitProcedure[];
  status: VisitStatus;
  temperature: number | null;
  notes: string | null;
  vet_name: string | null;
  next_visit_date: string | null;
  isFollowUp: boolean;
  /** Linked treatments / vaccinations (visit_id). */
  records: VisitRecord[];
  /** Procedure types that already have a linked treatment. */
  treatmentTypes: ProcedureType[];
  hasVaccination: boolean;
  hasInsemination: boolean;
  withdrawalMilk: boolean;
  withdrawalMeat: boolean;
  /** Set on visits generated by a sinchronizacijos protokolas (0025). */
  sync: { applicationId: string | null; protocolName: string | null; stepTitle: string | null; stepNo: number | null; stepTotal: number | null; plannedMedications: SyncStepMedication[] } | null;
};

type Disease = { id: string; name: string };

const TREATMENT_PROCEDURES: ProcedureType[] = ["apziura", "gydymas", "profilaktika"];
const TREATMENT_BUTTON_LABEL: Record<ProcedureType, string> = {
  apziura: "Įrašyti apžiūrą",
  gydymas: "Įrašyti gydymą",
  profilaktika: "Įrašyti profilaktiką",
  sinchronizacija: "Įrašyti sinchronizacijos žingsnį",
};

// One visit — the scheduling/status wrapper. Tagged Gydymas / Profilaktika /
// Apžiūra / Vakcina procedures that have no record yet offer a button into
// the normal treatment / vaccination dialog, locked to this visit's animal
// and linked back atomically (create_*_for_visit, 0018) — stock is consumed
// there through FEFO, never by the visit itself.
export function VisitCard({
  visit,
  today,
  diseases,
  treatmentProducts,
  vaccineProducts,
  sperm,
  gloves,
  currentVetName,
  canWrite,
}: {
  visit: VisitCardData;
  today: string;
  diseases: Disease[];
  treatmentProducts: Product[];
  vaccineProducts: Product[];
  sperm: SemenProduct[];
  gloves: SemenProduct[];
  currentVetName: string | null;
  canWrite: boolean;
}) {
  const [statusState, statusAction, statusPending] = useActionState<ActionResult | null, FormData>(updateVisitStatus, null);
  const [deleteState, deleteAction, deletePending] = useActionState<ActionResult | null, FormData>(deleteVisit, null);
  const [cancelState, cancelAction, cancelPending] = useActionState<ActionResult | null, FormData>(cancelSyncApplication, null);
  const busy = statusPending || deletePending || cancelPending;
  const error =
    (statusState && !statusState.ok && statusState.error) ||
    (deleteState && !deleteState.ok && deleteState.error) ||
    (cancelState && !cancelState.ok && cancelState.error) ||
    null;

  const isOpen = OPEN_VISIT_STATUSES.includes(visit.status);
  const isOverdue = isOpen && vilniusDay(visit.visit_datetime) < today;
  const pendingTreatments = visit.procedures.filter(
    (p): p is ProcedureType => (TREATMENT_PROCEDURES as string[]).includes(p) && !visit.treatmentTypes.includes(p as ProcedureType),
  );
  const needsVaccination = visit.procedures.includes("vakcina") && !visit.hasVaccination;
  const needsInsemination = visit.procedures.includes("sekinimas") && !visit.hasInsemination;
  // A sync step with planned medicine is recorded as a treatment (FEFO stock, karencija);
  // a step without medicine has no record and is closed with "Atlikta".
  const sync = visit.sync;
  const needsSyncRecord = !!sync && sync.plannedMedications.length > 0 && !visit.treatmentTypes.includes("sinchronizacija");
  const productName = (id: string) => treatmentProducts.find((p) => p.id === id)?.name ?? "Produktas";

  return (
    <div className={`space-y-2 rounded-panel border p-3 ${isOverdue ? "border-danger/40 bg-danger-soft/30" : "border-border bg-surface"}`}>
      <div className="flex items-start justify-between gap-2">
        <div className="min-w-0">
          <Link href={`/veterinarija/gyvunai/${visit.animal_id}`} className="text-[14px] font-semibold text-text-primary hover:underline">
            {animalLabel(visit)}
          </Link>
          {visit.group_name && <span className="ml-1.5 text-[11px] text-text-muted">{visit.group_name}</span>}
          <p className="text-[12px] text-text-muted">{formatDateTime(visit.visit_datetime)}</p>
        </div>
        <Badge tone={isOverdue ? "danger" : VISIT_STATUS_TONE[visit.status]}>{isOverdue ? "Praleistas" : VISIT_STATUS_LABELS[visit.status]}</Badge>
      </div>

      <div className="flex flex-wrap gap-1">
        {visit.procedures.map((p) => (
          <Badge key={p} tone="neutral">
            {VISIT_PROCEDURE_LABELS[p]}
          </Badge>
        ))}
        {visit.isFollowUp && <Badge tone="accent">Pakartotinis</Badge>}
        {sync && (
          <Badge tone="accent">
            <Repeat className="size-3" /> {sync.protocolName ?? "Protokolas"}
            {sync.stepNo && sync.stepTotal ? ` · ${sync.stepNo}/${sync.stepTotal}` : ""}
          </Badge>
        )}
        {visit.withdrawalMilk && <Badge tone="warning">Karencija: pienas</Badge>}
        {visit.withdrawalMeat && <Badge tone="danger">Karencija: mėsa</Badge>}
      </div>

      {sync?.stepTitle && <p className="text-[13px] font-medium text-text-primary">{sync.stepTitle}</p>}
      {sync && sync.plannedMedications.length > 0 && (
        <div className="flex flex-wrap gap-1">
          {sync.plannedMedications.map((m, i) => (
            <Badge key={i} tone="neutral" title="Planuojamas vaistas (atsargos nurašomos įrašant žingsnį)">
              {productName(m.product_id)} · {formatQty(m.qty, m.unit)}
            </Badge>
          ))}
        </div>
      )}
      {visit.temperature != null && <p className="text-[12px] text-text-secondary">Temperatūra: {visit.temperature} °C</p>}
      {visit.notes && <p className="text-[12px] text-text-secondary">{visit.notes}</p>}
      {visit.records.length > 0 && (
        <ul className="space-y-1.5">
          {visit.records.map((r) => (
            <li key={`${r.kind}-${r.id}`} className="rounded-control bg-surface-secondary px-2.5 py-1.5 text-[12px] text-text-secondary">
              <p>
                <span className="font-semibold text-text-primary">{r.label}</span>
                {r.detail ? ` · ${r.detail}` : ""}
              </p>
              {r.lines.length > 0 && (
                <ul className="mt-0.5 space-y-0.5">
                  {r.lines.map((line, i) => (
                    <li key={i} className="flex gap-1.5">
                      <span className="text-text-muted">•</span>
                      <span>{line}</span>
                    </li>
                  ))}
                </ul>
              )}
              {(r.karencijaMilk || r.karencijaMeat || r.outcome) && (
                <p className="mt-1 flex flex-wrap gap-x-3 gap-y-0.5 text-[11.5px]">
                  {r.karencijaMilk && <span className="text-warning">🥛 iki {formatDate(r.karencijaMilk)}</span>}
                  {r.karencijaMeat && <span className="text-danger">🥩 iki {formatDate(r.karencijaMeat)}</span>}
                  {r.outcome && <span>Baigtis: {r.outcome}</span>}
                </p>
              )}
            </li>
          ))}
        </ul>
      )}
      {visit.next_visit_date && <p className="text-[12px] text-text-secondary">Kitas vizitas: {formatDate(visit.next_visit_date)}</p>}
      {visit.vet_name && <p className="text-[11px] text-text-muted">{visit.vet_name}</p>}
      {error && <p className="text-[12px] text-danger">{error}</p>}

      {canWrite && (
        <div className="flex flex-wrap items-center gap-1.5 border-t border-border pt-2">
          {isOpen &&
            pendingTreatments.map((type) => (
              <NewTreatmentDialog
                key={type}
                animalId={visit.animal_id}
                diseases={diseases}
                products={treatmentProducts}
                currentVetName={currentVetName}
                visitId={visit.id}
                fixedProcedureType={type}
                dialogTitle={TREATMENT_BUTTON_LABEL[type]}
                trigger={
                  <Button size="sm" variant="outline">
                    <Plus className="size-4" /> {TREATMENT_BUTTON_LABEL[type]}
                  </Button>
                }
              />
            ))}
          {isOpen && sync && needsSyncRecord && (
            <NewTreatmentDialog
              animalId={visit.animal_id}
              diseases={diseases}
              products={treatmentProducts}
              currentVetName={currentVetName}
              visitId={visit.id}
              fixedProcedureType="sinchronizacija"
              dialogTitle={`Sinchronizacijos žingsnis: ${sync.stepTitle ?? ""}`}
              initialDiagnosis={[sync.protocolName, sync.stepTitle].filter(Boolean).join(" — ")}
              initialMedications={sync.plannedMedications.map((m) => ({ product_id: m.product_id, qty: m.qty, route: m.administration_route }))}
              trigger={
                <Button size="sm" variant="outline">
                  <Plus className="size-4" /> Įrašyti žingsnį
                </Button>
              }
            />
          )}
          {isOpen && needsInsemination && (
            <NewInseminationDialog
              animalId={visit.animal_id}
              sperm={sperm}
              gloves={gloves}
              currentVetName={currentVetName}
              visitId={visit.id}
              trigger={
                <Button size="sm" variant="outline">
                  <Dna className="size-4" /> Įrašyti sėklinimą
                </Button>
              }
            />
          )}
          {isOpen && needsVaccination && (
            <NewVaccinationDialog
              animalId={visit.animal_id}
              products={vaccineProducts}
              currentVetName={currentVetName}
              visitId={visit.id}
              trigger={
                <Button size="sm" variant="outline">
                  <Plus className="size-4" /> Įrašyti vakcinaciją
                </Button>
              }
            />
          )}
          {isOpen && (
            <form action={statusAction}>
              <input type="hidden" name="visit_id" value={visit.id} />
              <Button size="sm" variant="outline" name="status" value="baigtas" disabled={busy}>
                <Check className="size-4" /> Atlikta
              </Button>
            </form>
          )}
          {isOpen && (
            <form action={statusAction} className="flex gap-1.5">
              <input type="hidden" name="visit_id" value={visit.id} />
              <Button size="sm" variant="ghost" name="status" value="atsauktas" disabled={busy}>
                Atšaukti
              </Button>
              <Button size="sm" variant="ghost" name="status" value="neivykes" disabled={busy}>
                Neįvyko
              </Button>
            </form>
          )}
          {isOpen && sync?.applicationId && (
            <form
              action={cancelAction}
              onSubmit={(e) => {
                if (!window.confirm("Nutraukti protokolą? Visi neatlikti jo žingsniai šiam gyvūnui bus atšaukti, atlikti įrašai išliks.")) e.preventDefault();
              }}
            >
              <input type="hidden" name="application_id" value={sync.applicationId} />
              <Button size="sm" variant="ghost" disabled={busy}>
                <XCircle className="size-4" /> Nutraukti protokolą
              </Button>
            </form>
          )}
          {!isOpen && (
            <form action={statusAction}>
              <input type="hidden" name="visit_id" value={visit.id} />
              <Button size="sm" variant="ghost" name="status" value="planuojamas" disabled={busy}>
                Atnaujinti į planuojamą
              </Button>
            </form>
          )}
          <form
            action={deleteAction}
            className="ml-auto"
            onSubmit={(e) => {
              if (!window.confirm("Pašalinti vizitą? Prie jo susieti gydymo / vakcinacijos įrašai išliks.")) e.preventDefault();
            }}
          >
            <input type="hidden" name="visit_id" value={visit.id} />
            <Button size="icon" variant="ghost" disabled={busy} aria-label="Pašalinti vizitą">
              <Trash2 className="size-4" />
            </Button>
          </form>
        </div>
      )}
    </div>
  );
}
